use cine;

insert into Gender(name, description) values ('Acción', 'Peliculas en las que prevalecen altas dosis de adrenalina');
insert into Gender(name, description) values ('Aventuras', 'Predominan las nuevas experiencias y situaciones');
insert into Gender(name, description) values ('Ciencia Ficcion', 'Basados en fenómenos imaginarios, en la ciencia ficción');
insert into Gender(name, description) values ('Comedia', 'Para provocar la risa o la alegría entre los espectadores');
insert into Gender(name, description) values ('Documental', 'Este género analiza un hecho o situación real sin ficcionarlo');
insert into Gender(name, description) values ('Drama', 'Se centran en desarrollar el problema o problemas entre los diferentes protagonistas');
insert into Gender(name, description) values ('Musical', 'Cortan su desarrollo natural con fragmentos musicales');
insert into Gender(name, description) values ('Suspenso', 'Conocido también como intriga');
insert into Gender(name, description) values ('Terror', 'Su principal objetivo es causar miedo, horror, incomodidad o preocupación');
-- select * from Gender;

insert into Movie(name, date_in, state, description, Gender_id_gender) values ('Nadie (Ilya Naishuller, 2021)', GETDATE(), 1, 'El vibrante Ilya Naishuller nos regala un paseo por la tranquila vida de Bob Odenkirk salpicado con maravillosas y violentas coreografías. ', 1);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('Fast & Furious 9', GETDATE(), 1, ' Y todo gracias a la familia (siempre creciente) de Vin Diesel.', 1);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('Los mercenarios 2', GETDATE(), 1, 'Más acción, más frases lapidarias y una verdadera escena de tiros donde Stallone, Schwarzenegger y Willis compartiesen munición y cobertura.', 1);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('13 asesinos', GETDATE(), 1, 'A ese ritmo, es normal que de vez en cuando se le cuele alguna de esas que no hay por dónde cogerla', 1);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('Misión imposible: Protocolo Fantasma', GETDATE(), 1, 'Fallout. Esta saga es eterna, aunque seguro que hay cosas que no sabías de Misión Imposible', 1);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('Mad Max: Furia en la carretera', GETDATE(), 1, 'Un australiano de 70 años, en pleno cansancio digital en 2015, dirigió la mejor película de persecuciones en años. ', 1);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('Star Wars: Episodio IV - Una nueva esperanza', GETDATE(), 1, 'Los gobernantes del Imperio Galáctico, capturan a la princesa Leia, quien posee datos confidenciales sobre su centro de operaciones militares, denominado "Estrella de la Muerte".', 2);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('Metropolis', GETDATE(), 1, 'El primer gran clásico mudo de la ciencia-ficción es un excelente despliegue de las posibilidades temáticas y narrativas del género.', 3);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('Palm Springs', GETDATE(), 1, 'una boda se repetirá una y otra vez hasta que los dos protagonistas, que son los únicos que saben que están atrapados en el bucle, descubran cómo salir.', 4);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('El caso Alcàsser', GETDATE(), 1, 'El caso criminal más mediático de la historia de España recibe un análisis, documentado y en el que tienen voz buena parte de los implicados en el crimen que paralizó España.', 5);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('El pianista', GETDATE(), 1, 'cuenta con Adrien Brody en el papel protagonista. Se trata de una adaptación fílmica de las memorias del músico polaco de origen judío Wladyslaw Szpilman.', 6);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('Cry-Baby', GETDATE(), 1, 'destrozaría a los Rebeldes de Coppola sin miramientos y una inolvidable maravilla pop que, de en broma que va, va súper en serio. ', 7);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('Sweet Girl', GETDATE(), 1, 'La codicia de una compañía farmacéutica le arrebató al amor de su vida. Ahora, su hija vive sin su madre, y él, sin justicia.', 8);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('Insidious', GETDATE(), 1, 'La primera y genuina película sobrenatural de James Wan de la década, aunque recuperaba detalles de su Dead Silence', 9);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('Cisne Negro', GETDATE(), 1, 'Pura paranoia de ecos de Polanski, giallo y Satoshi Kon en la que brilla una Natalie Portman rota que logra pasar de la angustia a la ira hasta dar miedo en su metamorfosis interna y externa.', 9);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('Kill List', GETDATE(), 1, 'El folk horror ya se ha establecido como término de uso y deshuso pero en realidad siempre ha estado ahí. ', 9);
insert into Movie(name, date_in, state, description, Gender_id_gender) values ('La cabaña en el bosque', GETDATE(), 1, 'Impulsada por su alucinante tramo final, esta comedia de terror suele considerarse mejor de lo que es, pero si deja un buen sabor de boca es porque su clímax ', 9);
-- select * from Movie;

insert into Cinema(name, description) values ('Sala1', 'Sala numero 1');
insert into Cinema(name, description) values ('Sala2', 'Sala numero 2');
insert into Cinema(name, description) values ('Sala3', 'Sala numero 3');
insert into Cinema(name, description) values ('Sala4', 'Sala numero 4');
insert into Cinema(name, description) values ('Sala5', 'Sala numero 5');
-- select * from Cinema;

insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 1, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 2, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 3, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 4, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 5, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 1, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 2, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 3, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 4, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 5, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 1, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 2, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 3, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 4, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 5, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 1, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 2, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 3, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 4, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 5, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 1, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 2, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 3, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 4, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 5, 1, 1);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 1, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 2, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 3, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 4, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 5, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 1, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 2, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 3, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 4, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 5, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 1, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 2, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 3, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 4, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 5, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 1, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 2, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 3, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 4, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 5, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 1, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 2, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 3, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 4, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 5, 1, 2);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 1, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 2, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 3, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 4, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 5, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 1, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 2, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 3, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 4, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 5, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 1, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 2, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 3, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 4, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 5, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 1, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 2, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 3, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 4, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 5, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 1, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 2, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 3, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 4, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 5, 1, 3);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 1, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 2, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 3, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 4, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 5, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 1, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 2, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 3, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 4, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 5, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 1, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 2, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 3, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 4, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 5, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 1, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 2, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 3, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 4, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 5, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 1, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 2, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 3, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 4, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 5, 1, 4);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 1, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 2, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 3, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 4, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (1, 5, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 1, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 2, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 3, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 4, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (2, 5, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 1, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 2, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 3, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 4, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (3, 5, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 1, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 2, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 3, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 4, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (4, 5, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 1, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 2, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 3, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 4, 1, 5);
insert into Seat(row, "column", state, Cinema_id_cinema) values (5, 5, 1, 5);
-- select * from Seat;

insert into Type_Function(name, description) values ('2D', 'Funciones en 2 dimensiones');
insert into Type_Function(name, description) values ('3D', 'Funciones en 3 dimensiones');
insert into Type_Function(name, description) values ('2D Recliner', 'Funciones en 2 dimensiones con butaca reclinable');
insert into Type_Function(name, description) values ('3D Recliner', 'Funciones en 3 dimensiones con butaca reclinable');
-- select * from Type_Function;

insert into Category(name, description) values ('Adultos', 'Caterogia de Adultos');
insert into Category(name, description) values ('Niño', 'Caterogia de Niño');
insert into Category(name, description) values ('Estudiante', 'Caterogia de Estudiante');
insert into Category(name, description) values ('Tercera Edad', 'Caterogia de Tercera Edad');
-- select * from Category;

insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (30, 1, 1);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (44, 2, 1);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (50, 3, 1);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (65, 4, 1);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (25, 1, 2);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (35, 2, 2);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (45, 3, 2);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (55, 4, 2);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (25, 1, 3);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (35, 2, 3);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (45, 3, 3);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (55, 4, 3);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (25, 1, 4);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (35, 2, 4);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (45, 3, 4);
insert into Cost(price, Type_Function_id_typefunction, Category_id_category) values (55, 4, 4);
-- select * from Cost;

insert into Customer(name, address, phone, nit) values ('Gerardo Perusina', 'Ciudad Guatemala', '11111111', '10000001');
insert into Customer(name, address, phone, nit) values ('Alberto Morataya', 'Naranjo', '22222222', '20000002');
insert into Customer(name, address, phone, nit) values ('Tatiana Gonzales', 'Mixco', '33333333', '30000003');
insert into Customer(name, address, phone, nit) values ('Tito Pacheco', 'Villa Nueva', '44444444', '40000004');
insert into Customer(name, address, phone, nit) values ('Cristiano Ronaldo', 'Ciudad Guatemala', '55555555', '50000005');
-- select * from Customer;

insert into Employee(name, address, phone, email) values ('Andres Zepeda', 'Ciudad Guatemala', '11111111', 'andres@mail.com');
insert into Employee(name, address, phone, email) values ('Marcos Lopez', 'Naranjo', '22222222', 'marcos@mail.com');
insert into Employee(name, address, phone, email) values ('Pedro Aguirre', 'Mixco', '33333333', 'pedro@mail.com');
insert into Employee(name, address, phone, email) values ('Andi Perez', 'Villa Nueva', '44444444', 'andi@mail.com');
insert into Employee(name, address, phone, email) values ('Huriel Gomez', 'Ciudad Guatemala', '55555555', 'huriel@mail.com');
-- select * from Employee;

insert into Pyment_Type(name, description) values ('Tarjeta', 'Pago haciendo uso de una tarjeta de credito o debito');
insert into Pyment_Type(name, description) values ('Efectivo', 'Pago por medio de efectivo');
-- select * from Pyment_Type;

insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-03 13:00:00', 9, 3, 1);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-03 13:00:00', 4, 2, 2);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-03 13:00:00', 5, 1, 1);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-03 14:00:00', 1, 5, 1);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-03 18:00:00', 2, 1, 1);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-03 18:00:00', 2, 2, 1);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-03 18:00:00', 2, 3, 2);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-03 18:00:00', 2, 4, 3);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-03 20:00:00', 2, 5, 4);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-04 14:00:00', 11, 2, 1);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-04 14:00:00', 11, 3, 1);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-04 14:00:00', 11, 4, 2);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-04 14:00:00', 13, 5, 4);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-05 13:00:00', 14, 3, 3);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-05 15:00:00', 15, 4, 2);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-05 18:00:00', 15, 1, 3);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-05 18:00:00', 16, 2, 1);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-06 19:00:00', 7, 1, 1);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-06 20:00:00', 8, 4, 1);
insert into Functionc(time, Movie_id_movie, Cinema_id_cinema, Type_Function_id_typefunction) values ('2021-10-06 20:00:00', 3, 5, 2);
-- select * from Functionc;

insert into Ticket(purchase_date, Customer_id_customer, Employee_id_employee, Seat_id_seat, Pyment_Type_id_pymenttype, Functionc_id_functionC, Cost_id_cost) values (GETDATE(), 1, 2, 12, 1, 2, 1);
insert into Ticket(purchase_date, Customer_id_customer, Employee_id_employee, Seat_id_seat, Pyment_Type_id_pymenttype, Functionc_id_functionC, Cost_id_cost) values (GETDATE(), 1, 2, 13, 1, 2, 1);
insert into Ticket(purchase_date, Customer_id_customer, Employee_id_employee, Seat_id_seat, Pyment_Type_id_pymenttype, Functionc_id_functionC, Cost_id_cost) values (GETDATE(), 1, 2, 14, 1, 2, 2);
insert into Ticket(purchase_date, Customer_id_customer, Employee_id_employee, Seat_id_seat, Pyment_Type_id_pymenttype, Functionc_id_functionC, Cost_id_cost) values (GETDATE(), 1, 2,  1, 2, 2, 5);
insert into Ticket(purchase_date, Customer_id_customer, Employee_id_employee, Seat_id_seat, Pyment_Type_id_pymenttype, Functionc_id_functionC, Cost_id_cost) values (GETDATE(), 3, 2, 20, 1, 10, 1);
insert into Ticket(purchase_date, Customer_id_customer, Employee_id_employee, Seat_id_seat, Pyment_Type_id_pymenttype, Functionc_id_functionC, Cost_id_cost) values (GETDATE(), 3, 1, 12, 2, 12, 3);

-- select * from Ticket;